final List<Map<String, dynamic>> allTeachers = [
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
];
