import 'package:control_panel_2/models/teacher_model.dart';

final List<Teacher> allTeachers = [
  Teacher(
    id: '1',
    firstName: 'أحمد',
    lastName: 'محمد',
    username: 'ahmed_mohamed',
    mobileNumber: '0966512347',
    educationLevel: 'ماجستير',
    specialization: 'الرياضيات',
    certificates: 'ماجستير في الرياضيات التطبيقية',
    experience: '5 سنوات',
    description: 'مدرس رياضيات متمرس',
    joinDate: DateTime(2023, 1, 15),
    rating: 4.5,
    isActive: true,
  ),
  Teacher(
    id: '2',
    firstName: 'فاطمة',
    lastName: 'علي',
    username: 'fatima_ali',
    mobileNumber: '0966502478',
    educationLevel: 'دكتوراه',
    specialization: 'الفيزياء',
    certificates: 'دكتوراه في الفيزياء النووية',
    experience: '8 سنوات',
    description: 'أستاذة الفيزياء بجامعة الملك سعود',
    joinDate: DateTime(2022, 11, 8),
    rating: 4.8,
    isActive: true,
  ),
  Teacher(
    id: '3',
    firstName: 'خالد',
    lastName: 'حسن',
    username: 'khaled_hassan',
    mobileNumber: '0966504589',
    educationLevel: 'بكالوريوس',
    specialization: 'الكيمياء',
    certificates: 'بكالوريوس في الكيمياء الصناعية',
    experience: '3 سنوات',
    description: 'مدرس كيمياء للمرحلة الثانوية',
    joinDate: DateTime(2023, 3, 22),
    rating: 4.2,
    isActive: true,
  ),
  Teacher(
    id: '4',
    firstName: 'نورا',
    lastName: 'عبدالله',
    username: 'nora_abdullah',
    mobileNumber: '0966545678',
    educationLevel: 'ماجستير',
    specialization: 'الأحياء',
    certificates: 'ماجستير في الأحياء الدقيقة',
    experience: '6 سنوات',
    description: 'مدرسة أحياء متخصصة في الأحياء الدقيقة',
    joinDate: DateTime(2022, 9, 30),
    rating: 4.6,
    isActive: true,
  ),
  Teacher(
    id: '5',
    firstName: 'يوسف',
    lastName: 'إبراهيم',
    username: 'youssef_ibrahim',
    mobileNumber: '0966505601',
    educationLevel: 'دكتوراه',
    specialization: 'اللغة العربية',
    certificates: 'دكتوراه في الأدب العربي',
    experience: '10 سنوات',
    description: 'أستاذ اللغة العربية وآدابها',
    joinDate: DateTime(2023, 5, 17),
    rating: 4.9,
    isActive: true,
  ),
  Teacher(
    id: '6',
    firstName: 'لمى',
    lastName: 'الكواري',
    username: 'lama_alqawari',
    mobileNumber: '0966507892',
    educationLevel: 'بكالوريوس',
    specialization: 'اللغة الإنجليزية',
    certificates: 'بكالوريوس في اللغة الإنجليزية وآدابها',
    experience: '4 سنوات',
    description: 'مدرسة لغة إنجليزية للمراحل المتوسطة',
    joinDate: DateTime(2023, 2, 10),
    rating: 4.3,
    isActive: false,
  ),
  Teacher(
    id: '7',
    firstName: 'عمر',
    lastName: 'راشد',
    username: 'omar_rashid',
    mobileNumber: '0966507890',
    educationLevel: 'ماجستير',
    specialization: 'التاريخ',
    certificates: 'ماجستير في التاريخ الإسلامي',
    experience: '7 سنوات',
    description: 'مدرس تاريخ متخصص في التاريخ الإسلامي',
    joinDate: DateTime(2022, 12, 5),
    rating: 4.7,
    isActive: true,
  ),
  Teacher(
    id: '8',
    firstName: 'سارة',
    lastName: 'خالد',
    username: 'sara_khaled',
    mobileNumber: '0966508934',
    educationLevel: 'دكتوراه',
    specialization: 'علم الحاسوب',
    certificates: 'دكتوراه في الذكاء الاصطناعي',
    experience: '9 سنوات',
    description: 'أستاذة علم الحاسوب وتخصص الذكاء الاصطناعي',
    joinDate: DateTime(2023, 4, 18),
    rating: 4.8,
    isActive: true,
  ),
];
