final List<Map<String, dynamic>> allTeachers = [
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 2,
    'name': 'فاطمة علي',
    'username': 'fatima_ali',
    'email': 'fatima@example.com',
    'joinDate': DateTime(2022, 11, 8),
  },
  {
    'id': 3,
    'name': 'خالد حسن',
    'username': 'khaled_hassan',
    'email': 'khaled@example.com',
    'joinDate': DateTime(2023, 3, 22),
  },
  {
    'id': 4,
    'name': 'نورا عبدالله',
    'username': 'nora_abdullah',
    'email': 'nora@example.com',
    'joinDate': DateTime(2022, 9, 30),
  },
  {
    'id': 5,
    'name': 'يوسف إبراهيم',
    'username': 'youssef_ibrahim',
    'email': 'youssef@example.com',
    'joinDate': DateTime(2023, 5, 17),
  },
  {
    'id': 6,
    'name': 'لمى الكواري',
    'username': 'lama_alqawari',
    'email': 'lama@example.com',
    'joinDate': DateTime(2023, 2, 10),
  },
  {
    'id': 7,
    'name': 'عمر راشد',
    'username': 'omar_rashid',
    'email': 'omar@example.com',
    'joinDate': DateTime(2022, 12, 5),
  },
  {
    'id': 8,
    'name': 'سارة خالد',
    'username': 'sara_khaled',
    'email': 'sara@example.com',
    'joinDate': DateTime(2023, 4, 18),
  },
];
