final List<Map<String, dynamic>> allStudents = [
  {
    'id': 1,
    'name': 'أحمد محمد',
    'username': 'ahmed_mohamed',
    'email': 'ahmed@example.com',
    'status': 'تثبيت',
    'joinDate': DateTime(2023, 1, 15),
  },
  {
    'id': 2,
    'name': 'فاطمة علي',
    'username': 'fatima_ali',
    'email': 'fatima@example.com',
    'status': 'تسجيل',
    'joinDate': DateTime(2023, 3, 10),
  },
  {
    'id': 3,
    'name': 'خالد حسن',
    'username': 'khaled_hassan',
    'email': 'khaled@example.com',
    'status': 'تسجيل',
    'joinDate': DateTime(2023, 2, 20),
  },
  {
    'id': 4,
    'name': 'نورا عبدالله',
    'username': 'nora_abdullah',
    'email': 'nora@example.com',
    'status': 'انسحاب',
    'joinDate': DateTime(2023, 4, 5),
  },
  {
    'id': 5,
    'name': 'عمر إبراهيم',
    'username': 'omar_ibrahim',
    'email': 'omar@example.com',
    'status': 'تثبيت',
    'joinDate': DateTime(2023, 1, 30),
  },
  {
    'id': 6,
    'name': 'ياسمين محمود',
    'username': 'yasmin_mahmoud',
    'email': 'yasmin@example.com',
    'status': 'تسجيل',
    'joinDate': DateTime(2023, 5, 15),
  },
  {
    'id': 7,
    'name': 'محمود رشيد',
    'username': 'mahmoud_rashid',
    'email': 'mahmoud@example.com',
    'status': 'تسجيل',
    'joinDate': DateTime(2023, 6, 1),
  },
  {
    'id': 8,
    'name': 'سارة كمال',
    'username': 'sara_kamal',
    'email': 'sara@example.com',
    'status': 'انسحاب',
    'joinDate': DateTime(2023, 4, 20),
  },
];
