import 'package:control_panel_2/models/financial_reciept_model.dart';

final List<FinancialReciept> allReceipts = [
  FinancialReciept(
    number: 'FR001',
    type: 'دفع',
    date: '2025-08-15',
    person: 'أحمد العلي',
    item: 'كورس',
    service: 'دورة Flutter المتقدمة',
    ammount: '250000',
    reason: null,
  ),
  FinancialReciept(
    number: 'FR002',
    type: 'ارتجاع',
    date: '2025-08-14',
    person: 'ليلى حسن',
    item: 'رحلة',
    service: 'رحلة إلى تدمر',
    ammount: '150000',
    reason: 'تم إلغاء الرحلة بسبب الظروف الجوية',
  ),
  FinancialReciept(
    number: 'FR003',
    type: 'صرف',
    date: '2025-08-13',
    person: 'مروان يوسف',
    item: 'راتب موظف',
    service: null,
    ammount: '300000',
    reason: null,
  ),
  FinancialReciept(
    number: 'FR004',
    type: 'دفع',
    date: '2025-08-12',
    person: 'سارة إبراهيم',
    item: 'شهادة',
    service: 'شهادة مشاركة في مؤتمر البرمجة',
    ammount: '50000',
    reason: null,
  ),
  FinancialReciept(
    number: 'FR005',
    type: 'صرف',
    date: '2025-08-11',
    person: 'شركة التقنيات الحديثة',
    item: 'مشتريات',
    service: null,
    ammount: '450000',
    reason: null,
  ),
];
